#ifndef EVENT_HPP_
#define EVENT_HPP_

enum class Event
{
    IDLE,
    TRIGGER_SIMULATE_SINGLE,
    TRIGGER_SIMULATE_DOUBLE,
    TRIGGER_SIMULATE_SINGLE_TWICE_SEND,
    TRIGGER_SIMULATE_SINGLE_TWICE_RECEIVE,
    TRIGGER_SIMULATE_SINGLE_FAILED,
    SEND,
    RECEIVED
};

#endif